export const azureRules = [
    {
        "category": "App Service",
        "resource": "Linux App Service",
        "option": "Failed Request Tracing Enabled",
        "type": "로깅 모니터링",
        "description": "실패한 요청 정보 추적 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "App Service",
        "resource": "Linux App Service",
        "option": "Detailed Error Messages Enabled",
        "type": "로깅 모니터링",
        "description": "오류 페이지 저장 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "App Service",
        "resource": "Linux App Service",
        "option": "Auth Settings Enabled",
        "type": "사용자 확인 및 인증",
        "description": "인증 비활성화",
        "risk": "medium",
        "iso": "8.1",
        "csap": "10.3.3.",
        "isms": "2.5",
        "evaluation": "7.3.1"
    },
    {
        "category": "App Service",
        "resource": "Linux App Service\n",
        "option": "Ftps State",
        "type": "접근 통제",
        "description": "암호화되지 않는 ftp 프로토콜 허용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "App Service",
        "resource": "Linux App Service ",
        "option": "Http2 Enabled",
        "type": "네트워크 보안",
        "description": "http2 미적용",
        "risk": "low",
        "iso": "8.1",
        "csap": "11.1.1",
        "isms": "2.10",
        "evaluation": "8.3.1"
    },
    {
        "category": "App Service",
        "resource": "Service Pllaan",
        "option": "Sku Tier",
        "type": "네트워크 보안",
        "description": "always on 설정이 비활성화된 sku 사용",
        "risk": "low",
        "iso": "8.1",
        "csap": "6.2.2.",
        "isms": "2.9",
        "evaluation": "5.2.1"
    },
    {
        "category": "App Service",
        "resource": "Windows App Service",
        "option": "Failed Request Tracing Enabled",
        "type": "로깅 모니터링",
        "description": "실패한 요청 정보 추적 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "App Service",
        "resource": "Windows App Service",
        "option": "Detailed Error Messages Enabled",
        "type": "로깅 모니터링",
        "description": "오류 페이지 저장 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "App Service",
        "resource": "Windows App Service",
        "option": "Auth Settings Enabled",
        "type": "사용자 확인 및 인증",
        "description": "인증 비활성화",
        "risk": "medium",
        "iso": "8.1",
        "csap": "10.3.3.",
        "isms": "2.5",
        "evaluation": "7.3.1"
    },
    {
        "category": "App Service",
        "resource": "Windows App Service",
        "option": "Http2 Enabled",
        "type": "네트워크 보안",
        "description": "http2 미적용",
        "risk": "low",
        "iso": "8.1",
        "csap": "11.1.1",
        "isms": "2.10",
        "evaluation": "8.3.1"
    },
    {
        "category": "App Service",
        "resource": "Windows App Service",
        "option": "Ftps State",
        "type": "접근 통제",
        "description": "암호화되지 않는 ftp 프로토콜 허용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Compute",
        "resource": "Linux Virtual Machine Sacle Set",
        "option": "Enable Ssh Key Authentication",
        "type": "사용자 확인 및 인증",
        "description": "ssh 키 인증 미사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Compute",
        "resource": "Linux Virtual Mamchine",
        "option": "Enable Ssh Key Authentication",
        "type": "사용자 확인 및 인증",
        "description": "ssh 키 인증 미사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Container",
        "resource": "Container Registry",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Container",
        "resource": "Container Registry",
        "option": "Admiin Enabled",
        "type": "접근 통제",
        "description": "관리자 활성화",
        "risk": "medium",
        "iso": "8.1",
        "csap": "10.2.1.",
        "isms": "2.5",
        "evaluation": "7.2.2"
    },
    {
        "category": "Container",
        "resource": "Kubernetes",
        "option": "Default Node Pool > Enable Node Public Ip",
        "type": "접근 통제",
        "description": "노트 public ip 활성화",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Container",
        "resource": "Kubernetes Cluster",
        "option": "Sku Tier",
        "type": "네트워크 보안",
        "description": "Free sku는 Uptime SLA 서비스 미제공",
        "risk": "high",
        "iso": "8.1",
        "csap": "6.2.2.",
        "isms": "2.9",
        "evaluation": "5.2.1"
    },
    {
        "category": "Container",
        "resource": "Kubernetes Cluster",
        "option": "Default Node Pool > Max Pods",
        "type": "네트워크 보안",
        "description": "생성 가능한 최대 파드 개수 부족",
        "risk": "high",
        "iso": "8.1",
        "csap": "6.2.2.",
        "isms": "2.9",
        "evaluation": "5.2.1"
    },
    {
        "category": "Container",
        "resource": "Kubernetes Cluster",
        "option": "Api Server Authorized Ip Ranges",
        "type": "접근 통제",
        "description": "접근 가능 ip 전체 범위 설정",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Container",
        "resource": "Kubernetes Cluster",
        "option": "Network Policy",
        "type": "네트워크 보안",
        "description": "network policy 미설정",
        "risk": "critical",
        "iso": "8.1",
        "csap": "11.1.1",
        "isms": "2.10",
        "evaluation": "8.3.1"
    },
    {
        "category": "Cosmosdb",
        "resource": "Cosmosdb Cassandra,\nCosmosdb Gremlin,\nCosmosdb Mongo,\nCosmosdb Sql,\nCosmosdb Table",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Auditing Policy > Enable Storage Destination, Auditing Policy > Enable Log Analytics Destination",
        "type": "로깅 모니터링",
        "description": "감사 정책 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Enable Storage Destination, Storage Retention Days",
        "type": "로깅 모니터링",
        "description": "로그 보관 기간 짧음",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Security Alert Policy > Alert Policy State, Security Alert Policy > Disabled Alerts",
        "type": "로깅 모니터링",
        "description": "특정 위협 알림 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Security Alert Policy > Alert Policy State, Security Alert Policy > Alert Retention Days",
        "type": "로깅 모니터링",
        "description": "로그 보관 기간 짧음",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Security Alert Policy > Alert Policy State, Security Alert Policy > Alert Email Addresses",
        "type": "로깅 모니터링",
        "description": "보안 경고 받을 이메일 주소 미설정",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Security Alert Policy > Alert Policy State, Security Alert Policy > Alert Email Account Admins",
        "type": "로깅 모니터링",
        "description": "구독자 보안 경고 비활성화",
        "risk": "low",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Security Alert Policy > Alert Policy State",
        "type": "로깅 모니터링",
        "description": "security alert 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mssql Server",
        "option": "Minimum Tls Version",
        "type": "암호화",
        "description": "취약한 tls 버전 사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Database",
        "resource": "Mysql",
        "option": "Threat Detection Enabled",
        "type": "로깅 모니터링",
        "description": "위협 탐지 비활성화",
        "risk": "high",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mysql",
        "option": "Firewall Rule > Start Ip Address, Firewall Reule > End Ip Address",
        "type": "접근 통제",
        "description": "접근 가능 ip 전체 범위 설정",
        "risk": "high",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Mysql",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Mysql",
        "option": "Minimum Tls Version",
        "type": "암호화",
        "description": "취약한 tls 버전 사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Database",
        "resource": "Mysql",
        "option": "Ssl Enforcement Enabled",
        "type": "네트워크 보안",
        "description": "암호화 연결 미적용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Database",
        "resource": "Mysql Database",
        "option": "Enable Storage Destination, Sorage Retention Days",
        "type": "로깅 모니터링",
        "description": "로그 보관 기간 짧음",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mysql Database",
        "option": "Auditing Policy > Enable Storage Destination, Auditing Policy > Enable Log Analytics\nDestination",
        "type": "로깅 모니터링",
        "description": "감사 정책 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Mysql Database",
        "option": "Zone Redundant",
        "type": "데이터 보호",
        "description": "zone 중복성 비활성화",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.1.4.",
        "isms": "2.9",
        "evaluation": "10.1.4"
    },
    {
        "category": "Database",
        "resource": "Mysql Flexible",
        "option": "Firewall Rule > Start Ip Address, Firewall Reule > End Ip Address",
        "type": "접근 통제",
        "description": "접근 가능 ip 전체 범위 설정",
        "risk": "high",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Mysql Server",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Configuration > Log Retention",
        "type": "로깅 모니터링",
        "description": "로그 보존 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Configuration > Connection Throttling",
        "type": "로깅 모니터링",
        "description": "connection throttling 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Configuration > Log Checkpoint",
        "type": "로깅 모니터링",
        "description": "log checkpoint 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Configuration > Log Connections",
        "type": "로깅 모니터링",
        "description": "log connections 설정 비활성화",
        "risk": "medium",
        "iso": "9.1",
        "csap": "7.2.2",
        "isms": "2.11",
        "evaluation": "1.4.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Firewall Rule > Start Ip Address, Firewall Reule > End Ip Address",
        "type": "접근 통제",
        "description": "접근 가능 ip 전체 범위 설정",
        "risk": "high",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Minimum Tls Version",
        "type": "암호화",
        "description": "취약한 tls 버전 사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql",
        "option": "Ssl Enforcement Enabled",
        "type": "네트워크 보안",
        "description": "암호화 연결 미적용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql Flexible",
        "option": "Geo Redundant Backup Enabled",
        "type": "데이터 보호",
        "description": "지역 중복 백업 비활성화",
        "risk": "high",
        "iso": "8.1",
        "csap": "6.2.2.",
        "isms": "2.9",
        "evaluation": "5.2.1"
    },
    {
        "category": "Database",
        "resource": "Postgresql Flexible",
        "option": "Firewall Rule > Start Ip Address, Firewall Reule > End Ip Address",
        "type": "접근 통제",
        "description": "접근 가능 ip 전체 범위 설정",
        "risk": "high",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Key Vault",
        "resource": "Key Vault",
        "option": "Network Acl Action",
        "type": "접근 통제",
        "description": "설정한 ip와 일치하지 않는 경우 거부",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Key Vault",
        "resource": "Key Vault",
        "option": "Purge Protection Enabled",
        "type": "데이터 보호",
        "description": "제거 보호 비활성화",
        "risk": "medium",
        "iso": "8.1",
        "csap": "12.1.4.",
        "isms": "2.9",
        "evaluation": "10.1.4"
    },
    {
        "category": "Key Vault",
        "resource": "Key Vault",
        "option": "Key Vault Secret > Content Type",
        "type": "암호화",
        "description": "secret 내용 유형 미설정",
        "risk": "low",
        "iso": "8.1",
        "csap": "12.3.2.",
        "isms": "2.7",
        "evaluation": "10.2.2"
    },
    {
        "category": "Key Vault",
        "resource": "Key Vault",
        "option": "Key Vault Secret > Enabled Expiration Date",
        "type": "암호화",
        "description": "secret 만료 설정 비활성화",
        "risk": "low",
        "iso": "8.1",
        "csap": "12.3.2.",
        "isms": "2.7",
        "evaluation": "10.2.2"
    },
    {
        "category": "Key Vault",
        "resource": "Key Vault",
        "option": "Key Vault Key > Enabled Expiration Date",
        "type": "암호화",
        "description": "key 만료 설정 비활성화",
        "risk": "medium",
        "iso": "8.1",
        "csap": "12.3.2.",
        "isms": "2.7",
        "evaluation": "10.2.2"
    },
    {
        "category": "Network",
        "resource": "Application Gateway",
        "option": "Http Listner > Protocol",
        "type": "접근 통제",
        "description": "암호화 되지 않는 http 프로토콜 사용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Network",
        "resource": "Network Security Group",
        "option": "Security Rules > Direction, Security Rules > Access, Security Rules > Source Address Prefixes, Security Rules > Destination Port Rages",
        "type": "접근 통제",
        "description": "인터넷에서 FTP 액세스 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Network",
        "resource": "Network Security Group",
        "option": "Security Rules > Direction, Security Rules > Access, Security Rules > Source Address Prefixes, Security Rules > Destination Port Rages",
        "type": "접근 통제",
        "description": "인터넷에서 SSH 액세스 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Network",
        "resource": "Network Security Group",
        "option": "Security Rules > Direction, Security Rules > Access, Security Rules > Source Address Prefixes, Security Rules > Destination Port Rages",
        "type": "접근 통제",
        "description": "인터넷에서 HTTP 액세스 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Network",
        "resource": "Network Security Group",
        "option": "Security Rules > Direction, Security Rules > Access, Security Rules > Source Address Prefixes, Security Rules > Destination Port Rages",
        "type": "접근 통제",
        "description": "인터넷에서 RDP 액세스 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Network",
        "resource": "Network Security Group",
        "option": "Security Rules > Direction, Security Rules > Access, Security Rules > Source Address Prefixes / ",
        "type": "접근 통제",
        "description": "cidr 전체 노출",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Network",
        "resource": "Network Security Group",
        "option": "Security Rules > Direction, Security Rules > Access, Security Rules > Source Address Prefixes / ",
        "type": "접근 통제",
        "description": "cidr 전체 노출",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Network",
        "resource": "Web Application Firewall Policy",
        "option": "Owasp Version",
        "type": "데이터 보호",
        "description": "log4jshell를 방어하기 위한 rule이 부재한 버전 사용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "12.1.4.",
        "isms": "2.9",
        "evaluation": "10.1.4"
    },
    {
        "category": "Redis Cache",
        "resource": "Redis Cache",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Redis Cache",
        "resource": "Redis Cache",
        "option": "Sku Name",
        "type": " 데이터 보호",
        "description": "복제 기능을 제공하지 않는 sku 사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.1.4.",
        "isms": "2.9",
        "evaluation": "10.1.4"
    },
    {
        "category": "Redis Cache",
        "resource": "Redis Cache",
        "option": "Minimum Tls Version",
        "type": "암호화",
        "description": "취약한 tls 버전 사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Redis Cache",
        "resource": "Redis Cache",
        "option": "Enable Non Ssl Port",
        "type": "접근 통제",
        "description": "암호화 되지 않는 통신 허용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Storage",
        "resource": "Storage Account",
        "option": "Networking > Bypass",
        "type": "접근 통제",
        "description": "azure service 우회 불가능",
        "risk": "high",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Storage",
        "resource": "Storage Account",
        "option": "Storage Container > Container Access Type",
        "type": "접근 통제",
        "description": "공개 액세스 항목 설정",
        "risk": "high",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Storage",
        "resource": "Storage Account",
        "option": "Public Network Access Enabled",
        "type": "접근 통제",
        "description": "public 네트워크 접근 허용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "10.1.1.",
        "isms": "2.6",
        "evaluation": "7.1.1"
    },
    {
        "category": "Storage",
        "resource": "Storage Account",
        "option": "Minimum Tls Version",
        "type": "암호화",
        "description": "취약한 tls 버전 사용",
        "risk": "high",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    },
    {
        "category": "Storage",
        "resource": "Storage Account",
        "option": "Enable Https Traffic Only",
        "type": "접근 통제",
        "description": "암호화되지 않는 http 프로톹콜 사용",
        "risk": "critical",
        "iso": "8.1",
        "csap": "12.3.1.",
        "isms": "2.7",
        "evaluation": "10.2.1"
    }
]
