/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 문서 폴더(또는 versioned_docs/<version>)에서 사이드바 생성
    },
  ],
};
